utils_test.go

I had a version of these tests in my local `csiutils` package that I was using before `gocsi` was created. I see no harm moving them here.
Only difference I had was that in my utils, I did only allow a UDS for the network connection, and my tests checked for that. So I've modified `TestInvalidCSIEndpoint` to just look for junk/typo'd protocols instead.

Add tests for parsing of CSI_ENDPOINT

---

controller.go
csc/controller.go
csc/main.go
csc/node.go
interceptors_server.go

This patch includes the following fixes and updates:
* The `csc controllerpublishvolume` command can now accept the data used to construct a volume capability object.
* The library's `ControllerPublishVolume` function can now accept the address of a `csi.VolumeCapability` object.
* The server-side response logger checks for a nil response.

General Fixes and Updates

---

idempotent_interceptor.go
mount/mount.go
mount/mount_darwin.go
mount/mount_linux.go
mount/mount_utils.go
mount/mount_utils_test.go

This patch updates the way GetMounts collects mount information for Linux. Instead of using /proc/mounts the mount_namespaces feature present since Linux Kernel 2.2.26 at /proc/<pid>/mountinfo is leveraged. This method enables the addition of the Source field to the Info struct, providing a means to map a bind mount back to the source path and not just the device on which the original path exists.

GetMounts now uses /proc/self/mountinfo for Linux

---

idempotent_interceptor.go
trylock.go

This patch updates the idempotent interceptor to allow for the cases where the guarded operation returns an error. If it does, that call for that volume will be marked as in error and a subsequent, same call for that volume will bypass the idempotent guard. Not until the handler returns a successful operation will the idempotent guard take effect once again for that volume for that particular operation.

Idempotent Errors

---

Makefile
controller_test.go
interceptors_server_idemp.go
interceptors_server_request_id_injector.go
mock/provider/provider.go
mock/service/idemp.go
trylock.go

This patch refactors the idempotency interceptor to use twin locking domains based on the volume name and ID. Additionally, the interceptor has been optimized to no longer require name lookups for each operation.

Idempotency Interceptor Refactor

---

csc/cmd/controller_create_volume.go
csc/cmd/controller_delete_volume.go
csc/cmd/controller_get_capacity.go
csc/cmd/controller_list_volumes.go
csc/cmd/controller_publish_volume.go
csc/cmd/controller_unpublish_volume.go
csc/cmd/controller_validate_volume_capabilities.go
csc/cmd/flags.go
csc/cmd/node_publish_volume.go
csc/cmd/node_unpublish_volume.go
csc/cmd/root.go
csc/cmd/usage.go
csc/cmd/vartypes.go

This patch cleans up some of the CSC flags as well as no longer prints out the full help text when a command is in error.

Additional CSC Updates

---

controller_test.go
interceptors_idempotency.go
interceptors_logger.go
interceptors_spec_validator.go
mock/service/controller.go

This patch fixes a critical runtime error that occurred when a CSI SP returned a nil gRPC response value. Due to the way gRPC handles return values in combination with Go's [`interface{}`/`nil` comparison rules](https://golang.org/doc/faq#nil_error), it is not possible to determine if the response is nil using `obj == nil`. This patch provides a means of nil response detection that does not rely on reflection, but instead uses a pre-populated map of all of the CSI RPCs response types and their associated nil values.
The issue lies in the gRPC-generated code:
```go
func (c *controllerClient) DeleteVolume(ctx context.Context, in *DeleteVolumeRequest, opts ...grpc.CallOption) (*DeleteVolumeResponse, error) {
out := new(DeleteVolumeResponse)
err := grpc.Invoke(ctx, …
```

Fix for Panic on Nil gRPC Response

---

interceptors.go
interceptors_logger.go
interceptors_spec_validator.go

If the interface coming into the req or response logger was nil, a crash
occured during reflection. Make sure the reflected value is valid before
continuing.
Example crash:
```sh
panic: reflect: call of reflect.Value.Type on zero Value
goroutine 40 [running]:
reflect.Value.Type(0x0, 0x0, 0x0, 0x0, 0x0)
/Users/travis/.go/1.9.0/src/reflect/value.go:1688 +0x1a3
github.com/thecodeteam/csi-scaleio/vendor/github.com/thecodeteam/gocsi.rprintReqOrRep(0xb05c80, 0xc42013c7e0, 0x849340, 0x0)
/Users/travis/go/src/github.com/thecodeteam/csi-scaleio/vendor/github.com/thecodeteam/gocsi/interceptors_logger.go:158 +0xac
github.com/thecodeteam/csi-scaleio/vendor/github.com/thecodeteam/gocsi.(*loggingInterceptor).handle(0xc420180080, 0xb0dac0, 0xc4201769c0, 0x8c50a6, 0x1c, 0x86f2e0, 0xc42040ac40, …
```

Don't log response if response is nil

---

Makefile
interceptors.go
interceptors_spec_validator.go

This PR includes two changes:
This first patch includes minor adjustments to the previous commit that added the function and logic for `isResponseNil`.
Because Travis-CI's containers have limited resources, the Mock SP's idempotency provider's timeout needs to be increased from the default value of 0 to 1s. This ensures that lack of system resources will not prevent a single, non-concurrent RPC from failing due to an OpPending error.
FYI, @codenrhoden, I realized how Travis-CI resource exhaustion can lead to test failures due to `OpPending` errors for test cases with single, non-concurrent operations. First of all, **all** tests run on Travis-CI are run in parallel, meaning that even if we're not testing 1,000 concurrent `DeleteVolume` calls, a `DeleteVolume` test may be executed at the …

Minor updates

---

controller_test.go
csp/README.md
csp/csp.go
csp/csp.sh
csp/csp_interceptors.go
interceptors_idempotency.go
mock/provider/provider.go
mock/service/idemp.go

This patch adds a new function to `csp.StoragePlugin`:
```go
BeforeServe func(context.Context, *StoragePlugin, net.Listener) error
```
The `BeforeServe` function allows an SP to participate in the SP lifecycle and modify interceptors and/or server options before the gRPC server is started.

CSP BeforeServe

---

.travis.yml
Makefile
context.go
csp/csp.go
csp/csp.sh
csp/csp_envvars.go
csp/csp_interceptors.go
csp/csp_usage.go

This patch adds the option to specify an SP's plug-in information via the environment variable `X_CSI_PLUGIN_INFO`.

CSP GetPluginInfo

---

controller_test.go
csp/csp.go
csp/csp_envvars.go
errors.go
interceptors_idempotency.go
interceptors_spec_validator.go
mock/service/controller.go

This patch fixes an issue with the idempotency interceptor where it was considering a NotFound error as it relates to volumes to be cacheable and mark the current RPC in error. This patch changes the logic so that OpPending, NotFound, and AlreadyExists errors will not mark an RPC in error. The NotFound errors must be accompanied with an error message that has the prefix "volumeID=" since the NotFound error code is also used when the node specified by a node ID is not found.

Idempotency Interceptor Fixes & New Tests

---

csc/cmd/controller_get_capacity.go

get-capacity was missing the optional field for params.

Add --params flag to get-capacity

---

csp/csp.go
csp/csp_envvars.go

Plugins that can can be centralized will only want to run the Controller
or Node Service depending on the node. Add Env vars that enable that,
while still defaulting to running all services.

Add CSP ability to only run node/controller svc

---

csc/cmd/root.go
errors.go

This patch updates csc to use the gRPC exit code (if there is one) as the csc process's exit code. For example:
```shell
$ csc/csc -e csi.sock c ls
invalid request version: 0.0.0
Please use -h,--help for more information
$ echo $?
3
```
```shell
$ csc/csc -e csi.sock -v 0.1.0 c attach 4 --node-id 4 --cap 5,block
volume not found: 4
Please use -h,--help for more information
$ echo $?
5
```

csc: Use gRPC error code as exit code

---

interceptors_spec_validator.go

This patch fixes the spec validator as it was not checking the option to require the node ID, but rather doing it all the time.

Make Require Node ID respect its option

---

gocsi.sh

This path introduces the ability to specify a custom Git Source and Branch with the gocsi.sh file. A custom Git repo is specified with the environment variable `GOCSI_DEP_SOURCE` and a custom branch with `GOCSI_DEP_BRANCH`. Otherwise the primary repo and the `master` branch are used.

Custom Dep source for GoCSI with gocsi.sh

---

csc/cmd/controller_create_volume.go
csc/cmd/controller_delete_volume.go
csc/cmd/interceptors.go
csc/cmd/root.go
middleware.go
middleware/specvalidator/spec_validator.go
usage.go

This patch removes the feature of the spec validator middleware that is able to drop errors for the `CreateVolume` and `DeleteVolume` RPCs when a volume already exists or is not found. This feature is no longer relevant with the latest spec.

Remove Dropping of Errs for Create/Delete

---

README.md
envvars.go
gocsi.sh
middleware.go
middleware/specvalidator/spec_validator.go
mock/provider/provider.go
testing/gocsi_test.go
testing/identity_test.go
usage.go

This is a necessary and important change. An SP is capable of making changes to an underlying storage platform. The results of such changes are reflected in CSI response messages. Dropping these messages could render a client unable to acknowledge a change has occurred, and could potentially lead to further errors, such as data loss. This change enables response message validation while still allowing CSI clients to reconstitute the response data, even when it is marked in error.
This patch updates the way GoCSI's specification validation middleware handles response validation:
* Validating response messages against the CSI specification now is now   disabled by default. Use `X_CSI_SPEC_REP_VALIDATION=true` to enable  response validation.
* When enabled, response validation no longer …

Spec Validation for Response Msgs - Off & Detailed

---

middleware/serialvolume/serial_volume_locker.go
testing/controller_test.go

This patch updates the error code for pending operations returned by the serial volume access middleware to use Aborted instead of FailedPrecondition.
Related to container-storage-interface/spec#160.

Update Err Code for Pending Op to Aborted

---

.travis.yml

This patch allows the failure of the csi-sp build job. This is a temporary action until there is a way to use dep to pull from GitHub PR refs.

Allow failure of csi-sp build job

---

README.md

`services` -> `service` package.

README: package name typo

---

.travis.yml
Makefile

This patch updates the Makefile so that it tells gocsi.sh to use the current repo slug and commit when generating the Gokpkg.toml file.

Write Generated Gopkg.toml w Travis info

---

.gitignore
.travis.yml
Makefile

This patch updates the way dep is downloaded. Now dep's source tree is cloned into vendor and built from there using the forked version of dep with support for GH pull request commits.

Update CSI-SP Dep

---

.github/code_of_conduct.md
.github/contributing.md
.github/issue_template.md
CONTRIBUTING.md

This patch adds documents related to working on and contributing to GoCSI such as a code of conduct, issue template, and contributing guidelines.

Add Code of Conduct, Issue Template, & Contrib doc

---

csc/cmd/formats.go

This change is required because CSI spec renamed `VolumeInfo` to `Volume`
and `csc controller list-volumes` fails with template execution error.
```
template: t:1:37: executing "t" at <$v.VolumeInfo>: can't evaluate field VolumeInfo in type *csi.ListVolumesResponse_Entry
```
The vendored CSI code already has this change.
Refer: https://github.com/container-storage-interface/spec/issues/174

csc: Rename VolumeInfo to Volume in listVolumesFormat

---

csc/cmd/controller_publish_volume.go
csc/cmd/node_stage_volume.go

CSI ControllerPublishVolumeRequest supports passing Readonly attribute.
NodeStageVolumeRequest does not supports passing Readonly attribute.
This change removes that.

csc: Add --read-only to controller publish

---

csc/cmd/controller_create_snapshot.go
csc/cmd/formats.go
csc/cmd/root.go
mock/service/controller.go
mock/service/service.go
testing/controller_test.go

This implements create-snapshot for the controller csc command.  It adds a format template and the command itself.

Adding support for Controller CreateSnapshot RPC

---

csc/cmd/formats.go

On commit a6b15dc6c4481848a696f273fce50a929a02bc6c we updated to CSI
v1.0, but we didn't properly update the Snapshot fields, so we are
currently trying to access to fields that are no longer there: CreatedAt
and Status
These have been replaced with CreationTime and ReadyToUse.
This patch updates the code to use the right fields.

Fix #117: Snapshot listing doesn't work

---

README.md
csc/cmd/controller_publish_volume.go
csc/cmd/interceptors.go
csc/cmd/node_publish_volume.go
csc/cmd/node_stage_volume.go
csc/cmd/root.go
envvars.go
middleware.go
middleware/specvalidator/spec_validator.go
mock/provider/provider.go
usage.go

This patch brings csc more in line with the terminology used CSI 1.0 by
renameing "publish info" to "publish context" as was done in the spec.
The code was work before by remapping --pub-info to the PublishContext
field in the request, but this patch renames --pub-info (which doesn't
exist anymore) to --pub-context.

Rename PubInfo to Pub Context

---

.gitignore
.travis.yml
Gopkg.toml
Makefile

fixes #119 
This is a touch hacky, but I'm changing it as part of a subsequent PR to move to Go modules anyways. The `make csi-sp` test was failing because it was pulling in the latest CSI spec, rather than the one we had specified in the Gopkg.toml file. This wasn't an issue until code went in for CSI v1.1.0 that added new methods to the CSI controller interface. I think it is completely fair that for CI, makefile originated runs of csi-sp test, that we always use the `Gopkg.toml` file from the checked out version of the code. So I took advantage of a switch within `gocsi.sh` that doesn't write a new `Gopkg.toml` file if it already exists -- I had the Makefile just copy it directly.
When doing `make csi-sp`, we should always use the Gopkg.toml file from
the checked out source. The …

fix make csi-sp test

---

README.md
csc/cmd/controller_publish_volume.go
csc/cmd/interceptors.go
csc/cmd/node_get_info.go
csc/cmd/root.go
envvars.go
middleware.go
middleware/specvalidator/spec_validator.go
mock/provider/provider.go
mock/service/controller.go
testing/controller_test.go
testing/gocsi_test.go
usage.go

This patch removes the spec validator  option for requiring NodeID, as
the current CSI spec makes it explicitly required for both the
NodeGetInfoResponse and the ControllerPublishVolumeRequest, so there is
no point in having a option to enable this -- we should always check for
it.
Furthermore, NodeID is actually optional for the
ControllerUnpublishVolumeRequest, and when the NodeID is blank in that
scenario the controller is supposed to unplish the volume from all
nodes. So this patch updates the mock driver to have that behavior and
adds tests to verify it.

Make NodeID required where needed

---

README.md
envvars.go
middleware.go
middleware/specvalidator/spec_validator.go
usage.go

This patch adds a new option to explicitly disable the checking of CSI
message field lengths against the defined maximums found in the spec.
This is in direct response to the observation of COs not adhering to
this portion of the spec and commonly sending strings that are longer
than the current default limit of 128 bytes. This leads consumers to use
GoCSI with all spec validation disabled, which minimizes it's
usefulness.
Fixes #105

Add option to disable field length checking

---

csc/cmd/node_expand_volume.go

- In the original code, the command was added to `controllerCmd`. It should be added to `nodeCmd`. So actually we can not use the `nodeExpandVolumeCmd `. Here I fixed the bug
- According to https://github.com/container-storage-interface/spec/blob/master/spec.md#nodeexpandvolume, VolumePath is required. We must provide it when using `csc node expand`.

fix: enable node expand volume cmd

---

csc/cmd/formats.go

With this, `PluginCapability_VolumeExpansion` is not ignored by the
csc formatter when rendering the received plugin capability list.
Before:
```
CONTROLLER_SERVICE
```
After:
```
CONTROLLER_SERVICE
ONLINE
```

csc: Add format for volume expansion capability

---

README.md
envvars.go
middleware.go
middleware/logging/logging_interceptor.go
usage.go

For some users, the "VolumeContext" field may contain sensitive data
that should not be logged. To preserve backwards compatibility, we still
log all fields but "secrets" by default, but now add a flag that can be
used to explicitly disable logging of "Volume Context".

Add option to disable logging of VolumeContext

---

csc/cmd/controller_expand_volume.go
csc/cmd/controller_list_snapshots.go
csc/cmd/node_expand_volume.go
csc/cmd/node_get_volume_stats.go
go.mod
go.sum

This PR contains two commits. The first bumps the spec and dependencies to v1.2.0.
The second makes the associated updates to the `csc` command to pass new (optional) flags. Namely:
* Add optional secrets field to ListSnapshotsRequest
* Add optional staging_path to NodeGetVolumeStatsRequest and
NodeExpandVolumeRequest
* Add optional volume_capability to ControllerExpandVolumeRequest
and NodeExpandVolumeRequest

CSI spec 1.2.0

---

gocsi.go

When receiving a stop signal, it is possible that the GRPC server has
not yet been iniitialized. Verify that is has been before trying to stop
the server.
fixes #139

Don't call grpc stop before server initialized

---

csc/cmd/controller_expand_volume.go
csc/cmd/node_expand_volume.go

**The `expand-volume` panic  (#141) comes from trying to access uninitialized pointer value in flag setting. And this can be resolved by adjusting the `expandVolume` variable structure fields.
```
var expandVolume struct {
reqBytes int64
limBytes int64
volCap   *volumeCapabilitySliceArg
}
```
`volCap` is currently an uninitialized pointer variable so when `cobra` tries to parse arguments and set the variable, it ends up dereferencing nill pointer value. That said, the problem can be resolved by changing `volCap` type to `volumeCapabilitySliceArg` instead of its pointer type.
```
var expandVolume struct {
reqBytes int64
limBytes int64
volCap   volumeCapabilitySliceArg
}
```
And adjusting other functions dependent of this variable.
The same fix can be applied to `node_expand_volume.go` for …

expand volume fix
